1627448109907	Sync.LogManager	DEBUG	Flushing file log
1627448110027	Sync.LogManager	DEBUG	Log cleanup threshold time: 1626584110027
1627448110094	Sync.LogManager	DEBUG	Done deleting files.
1627448199879	Sync.Service	DEBUG	User-Agent: Firefox/90.0.2 (Linux aarch64) FxSync/1.92.0.20210723064703.desktop
1627448199884	Sync.Service	INFO	Starting sync at 2021-07-28 12:56:39 in browser session PhTV-Qampfzb
1627448199895	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1627448199961	Sync.Status	INFO	Resetting Status.
1627448199961	Sync.Status	DEBUG	Status.service: error.sync.failed_partial => success.status_ok
1627448199975	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1627448199976	FirefoxAccounts	DEBUG	getOAuthToken enter
1627448199995	FirefoxAccounts	TRACE	getCachedToken returning cached token
1627448199996	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1627448200002	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1627448214055	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1627448214064	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1627448214088	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/188195676/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1627448214092	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1627448214093	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1627448214097	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1627448214116	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1627448214228	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
