1625017465380	Sync.SyncScheduler	DEBUG	Next sync in 90000 ms. (why=schedule)
1625017555386	Sync.Service	DEBUG	User-Agent: Firefox/89.0.2 (Linux aarch64) FxSync/1.91.0.20210623132525.desktop
1625017555388	Sync.Service	INFO	Starting sync at 2021-06-30 09:45:55 in browser session T1-4iUfgC9pp
1625017555392	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1625017555456	Sync.Status	INFO	Resetting Status.
1625017555456	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1625017555463	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1625017555463	FirefoxAccounts	DEBUG	getOAuthToken enter
1625017555470	FirefoxAccounts	TRACE	getCachedToken returning cached token
1625017555470	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1625017555475	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1625017557607	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2147500036 - NS_ERROR_ABORT
1625017557609	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_ABORT\"  nsresult: \"0x80004004 (NS_ERROR_ABORT)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1625017557613	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/158373954/info/collections failed: [Exception... "The connection was established, but no data was ever received"  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "<unknown>"  data: no] No traceback available
1625017557615	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1625017557616	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1625017557618	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection was established, but no data was ever received"  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "<unknown>"  data: no] No traceback available
1625017557635	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1625017557644	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection was established, but no data was ever received"  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "<unknown>"  data: no] No traceback available
